# Generated by Django 6.0.6 on 2026-06-20 17:34

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Course',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=150)),
                ('level', models.CharField(choices=[('N5', 'JLPT N5 (Beginner)'), ('N4', 'JLPT N4 (Elementary)'), ('N3', 'JLPT N3 (Intermediate)'), ('N2', 'JLPT N2 (Pre-Advanced)'), ('N1', 'JLPT N1 (Advanced)')], default='N5', max_length=2)),
                ('description', models.TextField(help_text='Short summary shown on the homepage grid card')),
                ('syllabus', models.TextField(blank=True, help_text='Detailed Syllabus components. Separate modules by typing a new line.', null=True)),
                ('schedule_info', models.CharField(blank=True, help_text='e.g., Mon/Wed/Thur - 9:00 AM to 6:00 PM', max_length=200, null=True)),
                ('duration_weeks', models.IntegerField()),
                ('price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('is_published', models.BooleanField(default=True)),
            ],
        ),
        migrations.CreateModel(
            name='Inquiry',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fullname', models.CharField(max_length=100)),
                ('email', models.EmailField(max_length=254)),
                ('phone', models.CharField(max_length=20)),
                ('message', models.TextField()),
                ('submitted_at', models.DateTimeField(auto_now_add=True)),
                ('target_course', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='courses.course')),
            ],
            options={
                'verbose_name_plural': 'Inquiries',
            },
        ),
    ]
