# Generated by Django 6.0.6 on 2026-06-20 20:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='AboutPage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(default='About Our Academy', max_length=200)),
                ('subtitle', models.CharField(default='Empowering language learners to unlock professional opportunities.', max_length=300)),
                ('why_study_title', models.CharField(default='Why Study with Dream 11?', max_length=200)),
                ('why_study_text', models.TextField()),
            ],
            options={
                'verbose_name': 'About Page Content',
                'verbose_name_plural': 'About Page Content',
            },
        ),
        migrations.CreateModel(
            name='JLPTInfoPage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(default='JLPT Exam & Batch Schedule', max_length=200)),
                ('intro_text', models.TextField()),
                ('card_title', models.CharField(default='Next Exam Windows', max_length=200)),
                ('card_text', models.TextField()),
            ],
            options={
                'verbose_name': 'JLPT Info Page Settings',
                'verbose_name_plural': 'JLPT Info Page Settings',
            },
        ),
        migrations.CreateModel(
            name='ServiceItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('track_type', models.CharField(choices=[('LANGUAGE', 'Language (Blue)'), ('EDUCATION', 'Education (Green)'), ('SKILLED', 'Skilled Work (Yellow)'), ('TRAINING', 'Training (Purple)')], default='LANGUAGE', max_length=20)),
                ('title', models.CharField(help_text='e.g., Student Visa Processing', max_length=150)),
                ('description', models.TextField()),
                ('meta_label', models.CharField(help_text='e.g., Requirements', max_length=100)),
                ('meta_value', models.CharField(help_text='e.g., JLPT N4/A2 + Industry Pass', max_length=150)),
                ('order', models.IntegerField(default=0, help_text='Order to display on page.')),
            ],
            options={
                'verbose_name': 'Service Item Card',
                'ordering': ['order'],
            },
        ),
    ]
