# Generated by Django 6.0.6 on 2026-06-20 20:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0002_aboutpage_jlptinfopage_serviceitem'),
    ]

    operations = [
        migrations.CreateModel(
            name='SlideshowPhoto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('caption', models.CharField(help_text='Text overlay displayed on the photo.', max_length=200)),
                ('image', models.ImageField(help_text='Upload your academy photo here.', upload_to='slideshow/')),
                ('order', models.IntegerField(default=0, help_text='Order to display (0, 1, 2, 3).')),
            ],
            options={
                'verbose_name': 'Slideshow Photo',
                'verbose_name_plural': 'Slideshow Photos',
                'ordering': ['order'],
            },
        ),
    ]
