# Generated by Django 6.0.6 on 2026-06-25 15:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0003_slideshowphoto'),
    ]

    operations = [
        migrations.AlterField(
            model_name='course',
            name='level',
            field=models.CharField(choices=[('N5', 'JLPT N5 (Beginner)'), ('N4', 'JLPT N4 (Elementary)'), ('N3', 'JLPT N3 (Intermediate)'), ('N2', 'JLPT N2 (Pre-Advanced)'), ('N1', 'JLPT N1 (Advanced)'), ('All', 'On All Courser')], default='N5', max_length=10),
        ),
    ]
