# Generated by Django 6.0.6 on 2026-06-26 08:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0004_alter_course_level'),
    ]

    operations = [
        migrations.AddField(
            model_name='aboutpage',
            name='image',
            field=models.ImageField(blank=True, help_text='Upload a team or campus photo to display alongside your introduction text details.', null=True, upload_to='about/'),
        ),
        migrations.AlterField(
            model_name='course',
            name='description',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='course',
            name='level',
            field=models.CharField(choices=[('N5', 'JLPT N5 (Beginner)'), ('N4', 'JLPT N4 (Elementary)'), ('N3', 'JLPT N3 (Intermediate)'), ('N2', 'JLPT N2 (Pre-Advanced)'), ('N1', 'JLPT N1 (Advanced)'), ('ALL', 'All Courses (Special Batch)')], default='N5', max_length=20),
        ),
        migrations.AlterField(
            model_name='course',
            name='schedule_info',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='course',
            name='syllabus',
            field=models.TextField(blank=True, null=True),
        ),
    ]
