# Generated by Django 6.0.6 on 2026-06-26 14:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0005_aboutpage_image_alter_course_description_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='course',
            name='description',
            field=models.TextField(help_text='Short summary shown on the homepage grid card'),
        ),
        migrations.AlterField(
            model_name='course',
            name='level',
            field=models.CharField(choices=[('N5', 'JLPT N5 (Beginner)'), ('N4', 'JLPT N4 (Elementary)'), ('N3', 'JLPT N3 (Intermediate)'), ('N2', 'JLPT N2 (Pre-Advanced)'), ('N1', 'JLPT N1 (Advanced)'), ('All', 'On All Courser')], default='N5', max_length=10),
        ),
        migrations.AlterField(
            model_name='course',
            name='schedule_info',
            field=models.CharField(blank=True, help_text='e.g., Mon/Wed/Thur - 9:00 AM to 6:00 PM', max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='course',
            name='syllabus',
            field=models.TextField(blank=True, help_text='Detailed Syllabus components. Separate modules by typing a new line.', null=True),
        ),
    ]
