# Generated by Django 6.0.6 on 2026-06-26 14:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0006_alter_course_description_alter_course_level_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='aboutpage',
            name='image_title',
            field=models.CharField(blank=True, default='Our Campus & Team Workspace', help_text='A short title or caption to display directly underneath or above your uploaded photo.', max_length=150, null=True),
        ),
    ]
