# Generated by Django 6.0.6 on 2026-06-26 14:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0007_aboutpage_image_title'),
    ]

    operations = [
        migrations.CreateModel(
            name='TeamMember',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='e.g., Md. Arif Rahman', max_length=150)),
                ('designation', models.CharField(help_text='e.g., Chief Executive / Senior Instructor', max_length=150)),
                ('role_group', models.CharField(choices=[('1_CHAIRMAN', 'Chairman'), ('2_DIRECTOR', 'Director'), ('3_TEACHER', 'Teacher'), ('4_STAFF', 'Office Staff')], default='3_TEACHER', help_text='Determines hierarchical listing order.', max_length=20)),
                ('message', models.TextField(help_text='The personal voice or statement from this member.')),
                ('photo', models.ImageField(blank=True, help_text='Upload a professional profile portrait photograph.', null=True, upload_to='team/')),
                ('order', models.IntegerField(default=0, help_text='Custom sorting index parameter (0, 1, 2...).')),
            ],
            options={
                'verbose_name': 'Academy Leader & Staff',
                'verbose_name_plural': 'Academy Leaders & Staff',
                'ordering': ['role_group', 'order'],
            },
        ),
    ]
