# Generated by Django 6.0.6 on 2026-06-26 15:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0008_teammember'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='aboutpage',
            name='image',
        ),
        migrations.RemoveField(
            model_name='aboutpage',
            name='image_title',
        ),
    ]
